# To get started with Dependabot (dependency bot by github) version updates, 
# you'll need to specify which package ecosystems to update and where the 
# package manifests are located.

# Please see the documentation for all configuration options:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - N7K4

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - N7K4

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - N7K4

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - N7K4
  
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - N7K4
